# Generated by Django 4.2.28 on 2026-02-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0002_rename_tempprofilieidentityrelation_tempprofileidentityrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cppa_user_tracker.baseprofile')),
                ('discord_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cppa_user_tracker_discordprofile',
            },
            bases=('cppa_user_tracker.baseprofile',),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='type',
            field=models.CharField(choices=[('github', 'GitHub'), ('slack', 'Slack'), ('mailing_list', 'Mailing list'), ('wg21', 'WG21'), ('discord', 'Discord')], db_index=True, max_length=20),
        ),
    ]
