# Generated by Django 4.2.28 on 2026-02-24 22:01

from django.db import migrations, models
from django.db.models import Count, Min


def pre_migrate_dedupe_slack_user_ids(apps, _schema_editor):
    """
    Remove duplicate SlackUser rows per slack_user_id so the UNIQUE constraint
    can be applied. Keeps the first row per slack_user_id; reassigns FKs
    (Email, TempProfileIdentityRelation, and cppa_slack_tracker SlackChannelMembership /
    SlackChannelMembershipChangeLog / SlackChannel.creator / SlackMessage.user)
    to that canonical user, then deletes duplicate SlackUser and BaseProfile rows.
    Runs inside a transaction.
    Before reassigning, removes conflicting rows (canonical vs duplicate or
    duplicate vs duplicate) so unique constraints are not violated.
    """
    SlackUser = apps.get_model("cppa_user_tracker", "SlackUser")
    BaseProfile = apps.get_model("cppa_user_tracker", "BaseProfile")
    Email = apps.get_model("cppa_user_tracker", "Email")
    TempProfileIdentityRelation = apps.get_model(
        "cppa_user_tracker", "TempProfileIdentityRelation"
    )
    SlackChannelMembership = apps.get_model(
        "cppa_slack_tracker", "SlackChannelMembership"
    )
    SlackChannelMembershipChangeLog = apps.get_model(
        "cppa_slack_tracker", "SlackChannelMembershipChangeLog"
    )
    SlackChannel = apps.get_model("cppa_slack_tracker", "SlackChannel")
    SlackMessage = apps.get_model("cppa_slack_tracker", "SlackMessage")
    duplicates = (
        SlackUser.objects.values("slack_user_id")
        .annotate(n=Count("pk"))
        .filter(n__gt=1)
    )
    for dup_row in duplicates:
        user_id = dup_row["slack_user_id"]
        users = list(
            SlackUser.objects.filter(slack_user_id=user_id).order_by("pk")
        )
        if len(users) <= 1:
            continue
        canonical = users[0]
        duplicate_pks = [u.pk for u in users[1:]]
        if canonical.identity_id is None:
            fallback_identity_id = (
                SlackUser.objects.filter(pk__in=duplicate_pks)
                .exclude(identity_id__isnull=True)
                .values_list("identity_id", flat=True)
                .first()
            )
            if fallback_identity_id is not None:
                BaseProfile.objects.filter(pk=canonical.pk).update(
                    identity_id=fallback_identity_id
                )
        Email.objects.filter(base_profile_id__in=duplicate_pks).update(
            base_profile_id=canonical.pk
        )
        TempProfileIdentityRelation.objects.filter(
            base_profile_id__in=duplicate_pks
        ).update(base_profile_id=canonical.pk)
        user_scope = [canonical.pk, *duplicate_pks]
        for mem_row in (
            SlackChannelMembership.objects.filter(user_id__in=user_scope)
            .values("channel_id")
            .annotate(keep_pk=Min("pk"), n=Count("pk"))
            .filter(n__gt=1)
        ):
            SlackChannelMembership.objects.filter(
                user_id__in=user_scope,
                channel_id=mem_row["channel_id"],
            ).exclude(pk=mem_row["keep_pk"]).delete()
        SlackChannelMembership.objects.filter(user_id__in=duplicate_pks).update(
            user_id=canonical.pk
        )
        for log_row in (
            SlackChannelMembershipChangeLog.objects.filter(user_id__in=user_scope)
            .values("channel_id", "created_at")
            .annotate(keep_pk=Min("pk"), n=Count("pk"))
            .filter(n__gt=1)
        ):
            SlackChannelMembershipChangeLog.objects.filter(
                user_id__in=user_scope,
                channel_id=log_row["channel_id"],
                created_at=log_row["created_at"],
            ).exclude(pk=log_row["keep_pk"]).delete()
        SlackChannelMembershipChangeLog.objects.filter(
            user_id__in=duplicate_pks
        ).update(user_id=canonical.pk)
        SlackChannel.objects.filter(creator_id__in=duplicate_pks).update(
            creator_id=canonical.pk
        )
        SlackMessage.objects.filter(user_id__in=duplicate_pks).update(
            user_id=canonical.pk
        )
        SlackUser.objects.filter(pk__in=duplicate_pks).delete()
        BaseProfile.objects.filter(pk__in=duplicate_pks).delete()


def noop(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):
    """
    Dedupe SlackUser by slack_user_id, add unique constraint on slack_user_id,
    and normalize migration state for table names.

    The AlterModelTable(..., table=None) operations sync migration state to
    Django's default table names (app_label_modelname). Physical table names
    are unchanged: 0001/0002/0003 already created tables with those same
    names (e.g. cppa_user_tracker_baseprofile). No RENAME is executed; this
    avoids state drift with the current models, which do not set db_table.
    Run after RunPython dedupe so the unique constraint can be applied safely.
    """

    dependencies = [
        ("cppa_user_tracker", "0003_discordprofile_alter_baseprofile_type"),
        (
            "cppa_slack_tracker",
            "0003_alter_slackchannel_unique_team_channel_id",
        ),
    ]

    operations = [
        migrations.RunPython(pre_migrate_dedupe_slack_user_ids, noop),
        migrations.AlterField(
            model_name="slackuser",
            name="slack_user_id",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name="baseprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="discordprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="email",
            table=None,
        ),
        migrations.AlterModelTable(
            name="githubaccount",
            table=None,
        ),
        migrations.AlterModelTable(
            name="identity",
            table=None,
        ),
        migrations.AlterModelTable(
            name="mailinglistprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="slackuser",
            table=None,
        ),
        migrations.AlterModelTable(
            name="tempprofileidentityrelation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="tmpidentity",
            table=None,
        ),
        migrations.AlterModelTable(
            name="wg21paperauthorprofile",
            table=None,
        ),
    ]
