# Generated by Django 4.2.28 on 2026-03-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cppa_user_tracker", "0005_youtubespeaker_alter_baseprofile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackuser",
            name="slack_user_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
