# Generated by Django 4.2.28 on 2026-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost_library_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostlibraryversion',
            name='documentation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boostlibraryversion',
            name='key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
