# Generated by Django 4.2.28 on 2026-02-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cppa_user_tracker', '0002_rename_tempprofilieidentityrelation_tempprofileidentityrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('parent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('content', models.TextField(blank=True)),
                ('list_name', models.CharField(db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='mailing_list_messages', to='cppa_user_tracker.mailinglistprofile')),
            ],
            options={
                'verbose_name': 'Mailing list message',
                'verbose_name_plural': 'Mailing list messages',
                'db_table': 'boost_mailing_list_tracker_mailinglistmessage',
                'ordering': ['-sent_at'],
            },
        ),
    ]
