# Generated by Django 4.2.28 on 2026-02-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost_mailing_list_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistmessage',
            name='list_name',
            field=models.CharField(choices=[('boost-announce@lists.boost.org', 'Boost Announce'), ('boost-users@lists.boost.org', 'Boost Users'), ('boost@lists.boost.org', 'Boost')], db_index=True, max_length=255),
        ),
    ]
