# Generated by Django 4.2.28 on 2026-02-18 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cppa_user_tracker', '0002_rename_tempprofilieidentityrelation_tempprofileidentityrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('team_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slack Team',
                'verbose_name_plural': 'Slack Teams',
            },
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('channel_type', models.CharField(choices=[('public_channel', 'Public channel'), ('private_channel', 'Private channel'), ('mpim', 'Multi-party direct message'), ('im', 'Direct message')], db_index=True, help_text='Type of channel (public_channel, private_channel, mpim, im).', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, db_column='creator_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to='cppa_user_tracker.slackuser')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='cppa_slack_tracker.slackteam')),
            ],
            options={
                'verbose_name': 'Slack Channel',
                'verbose_name_plural': 'Slack Channels',
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(db_index=True, help_text='Slack message timestamp (unique per channel)', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('thread_ts', models.CharField(blank=True, db_index=True, help_text='Thread timestamp if this is a threaded message', max_length=50, null=True)),
                ('slack_message_created_at', models.DateTimeField(db_index=True)),
                ('slack_message_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cppa_slack_tracker.slackchannel')),
                ('user', models.ForeignKey(blank=True, db_column='slack_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='cppa_user_tracker.slackuser')),
            ],
            options={
                'verbose_name': 'Slack Message',
                'verbose_name_plural': 'Slack Messages',
                'unique_together': {('channel', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='SlackChannelMembershipChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joined', models.BooleanField(help_text='True if joined, False if left')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_changes', to='cppa_slack_tracker.slackchannel')),
                ('user', models.ForeignKey(db_column='slack_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='membership_changes', to='cppa_user_tracker.slackuser')),
            ],
            options={
                'verbose_name': 'Slack Channel Membership Change Log',
                'verbose_name_plural': 'Slack Channel Membership Change Logs',
                'unique_together': {('channel', 'user', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='SlackChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_restricted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cppa_slack_tracker.slackchannel')),
                ('user', models.ForeignKey(db_column='slack_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='cppa_user_tracker.slackuser')),
            ],
            options={
                'verbose_name': 'Slack Channel Membership',
                'verbose_name_plural': 'Slack Channel Memberships',
                'unique_together': {('channel', 'user')},
            },
        ),
    ]
