# Generated by Django 4.2.28 on 2026-02-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_slack_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackmessage',
            name='ts',
            field=models.CharField(db_index=True, help_text='Slack message timestamp (unique identifier)', max_length=50),
        ),
    ]
