# Generated by Django 4.2.28 on 2026-02-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_slack_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackchannel',
            name='channel_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='slackchannel',
            constraint=models.UniqueConstraint(fields=('team', 'channel_id'), name='unique_team_channel_id'),
        ),
    ]
