# Generated by Django 4.2.27 on 2026-02-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("github_activity_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatedReposByLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("all_repos", models.IntegerField(default=0)),
                ("significant_repos", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        db_column="language_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_repo_counts",
                        to="github_activity_tracker.language",
                    ),
                ),
            ],
            options={
                "db_table": "github_activity_tracker_createdreposbylanguage",
                "ordering": ["language", "year"],
            },
        ),
        migrations.AddConstraint(
            model_name="createdreposbylanguage",
            constraint=models.UniqueConstraint(
                fields=("language", "year"),
                name="github_activity_tracker_created_lang_year_uniq",
            ),
        ),
    ]

