# Generated by Django 4.2.28 on 2026-03-17 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_activity_tracker', '0002_createdreposbylanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubfile',
            name='previous_filename',
            field=models.ForeignKey(blank=True, db_column='previous_filename_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renamed_to', to='github_activity_tracker.githubfile'),
        ),
    ]
