# Generated by Django 4.2.28 on 2026-03-24 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "github_activity_tracker",
            "0003_githubfile_previous_filename_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="createdreposbylanguage",
            constraint=models.CheckConstraint(
                check=models.Q(("year__gte", 0)),
                name="github_activity_tracker_created_lang_year_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="createdreposbylanguage",
            constraint=models.CheckConstraint(
                check=models.Q(("all_repos__gte", 0)),
                name="github_activity_tracker_created_lang_all_repos_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="createdreposbylanguage",
            constraint=models.CheckConstraint(
                check=models.Q(("significant_repos__gte", 0)),
                name="github_activity_tracker_created_lang_sig_repos_non_negative",
            ),
        ),
    ]
