# Generated by Django 4.2.28 on 2026-02-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(db_index=True, unique=True)),
                ('channel_name', models.CharField(db_index=True, max_length=255)),
                ('channel_type', models.CharField(max_length=50)),
                ('topic', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discord_activity_tracker_discordchannel',
                'ordering': ['server', 'position', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(db_index=True, unique=True)),
                ('content', models.TextField(blank=True)),
                ('message_created_at', models.DateTimeField(db_index=True)),
                ('message_edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_urls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discord_activity_tracker_discordmessage',
                'ordering': ['channel', 'message_created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.BigIntegerField(db_index=True, unique=True)),
                ('server_name', models.CharField(db_index=True, max_length=255)),
                ('icon_url', models.URLField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discord_activity_tracker_discordserver',
                'ordering': ['server_name'],
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discord_activity_tracker_discorduser',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='DiscordReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='discord_activity_tracker.discordmessage')),
            ],
            options={
                'db_table': 'discord_activity_tracker_discordreaction',
            },
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discord_activity_tracker.discorduser'),
        ),
        migrations.AddField(
            model_name='discordmessage',
            name='channel',
            field=models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discord_activity_tracker.discordchannel'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='server',
            field=models.ForeignKey(db_column='server_id', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='discord_activity_tracker.discordserver'),
        ),
        migrations.AddConstraint(
            model_name='discordreaction',
            constraint=models.UniqueConstraint(fields=('message', 'emoji'), name='discord_activity_tracker_msg_emoji_uniq'),
        ),
        migrations.AddIndex(
            model_name='discordmessage',
            index=models.Index(fields=['channel', 'message_created_at'], name='discord_act_channel_b1b3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='discordmessage',
            index=models.Index(fields=['message_created_at'], name='discord_act_message_bfb7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='discordmessage',
            index=models.Index(fields=['is_deleted'], name='discord_act_is_dele_3b2257_idx'),
        ),
        migrations.AddIndex(
            model_name='discordchannel',
            index=models.Index(fields=['server', 'channel_name'], name='discord_act_server__3c1258_idx'),
        ),
        migrations.AddIndex(
            model_name='discordchannel',
            index=models.Index(fields=['last_activity_at'], name='discord_act_last_ac_87ebfd_idx'),
        ),
    ]
