# Generated by Django 4.2.28 on 2026-02-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cppa_user_tracker', '0003_discordprofile_alter_baseprofile_type'),
        ('discord_activity_tracker', '0002_migrate_users_to_discord_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='discord_messages', to='cppa_user_tracker.discordprofile'),
        ),
    ]
