# Generated by Django 4.2.28 on 2026-02-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boost_library_tracker', '0001_initial'),
        ('github_activity_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostExternalRepository',
            fields=[
                ('githubrepository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='github_activity_tracker.githubrepository')),
                ('boost_version', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_boost_embedded', models.BooleanField(default=False)),
                ('is_boost_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boost External Repository',
                'verbose_name_plural': 'Boost External Repositories',
                'db_table': 'boost_usage_tracker_boostexternalrepository',
                'ordering': ['repo_name'],
            },
            bases=('github_activity_tracker.githubrepository',),
        ),
        migrations.CreateModel(
            name='BoostUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_commit_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('excepted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boost_header', models.ForeignKey(db_column='boost_header_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_usages', to='boost_library_tracker.boostfile')),
                ('file_path', models.ForeignKey(db_column='file_path_id', on_delete=django.db.models.deletion.CASCADE, related_name='boost_usages', to='github_activity_tracker.githubfile')),
                ('repo', models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, related_name='boost_usages', to='boost_usage_tracker.boostexternalrepository')),
            ],
            options={
                'verbose_name': 'Boost Usage',
                'verbose_name_plural': 'Boost Usages',
                'db_table': 'boost_usage_tracker_boostusage',
                'ordering': ['repo', 'boost_header', 'file_path'],
            },
        ),
        migrations.AddConstraint(
            model_name='boostusage',
            constraint=models.UniqueConstraint(fields=('repo', 'boost_header', 'file_path'), name='boost_usage_tracker_usage_uniq'),
        ),
    ]
